"""init

Revision ID: eed112596dc8
Revises:
Create Date: 2025-11-25 11:07:15.728079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eed112596dc8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classes",
        sa.Column("num", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("num", name=op.f("pk_classes")),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("child", sa.String(), nullable=False),
        sa.Column("class_num", sa.Integer(), nullable=False),
        sa.Column("mother", sa.String(), nullable=True),
        sa.Column("father", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
    )
    op.create_index(
        op.f("ix_schedules_child"), "schedules", ["child"], unique=False
    )
    op.create_index(
        op.f("ix_schedules_date"), "schedules", ["date"], unique=False
    )
    op.create_table(
        "families",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("child", sa.String(), nullable=False),
        sa.Column("mother", sa.String(), nullable=False),
        sa.Column("father", sa.String(), nullable=True),
        sa.Column("class_num", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_num"],
            ["classes.num"],
            name=op.f("fk_families_class_num_classes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_families")),
    )
    op.create_index(
        op.f("ix_families_child"), "families", ["child"], unique=True
    )
    op.create_index(
        op.f("ix_families_father"), "families", ["father"], unique=False
    )
    op.create_index(
        op.f("ix_families_mother"), "families", ["mother"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_families_mother"), table_name="families")
    op.drop_index(op.f("ix_families_father"), table_name="families")
    op.drop_index(op.f("ix_families_child"), table_name="families")
    op.drop_table("families")
    op.drop_index(op.f("ix_schedules_date"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_child"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_table("classes")
    # ### end Alembic commands ###
